# pls do this so u stop using all our storage
# https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169
# docker-compose -f docker-compose.yml -f optional-service.yaml up
version: '3'

services:
  # Frontend Service
  vue: # name of service
    build: frontend # dir of dockerfile
    restart: unless-stopped
    tty: true
    ports:
    - "8080:80" # map ports
    networks:
    - app-network

  api:
    container_name: api
    restart: unless-stopped
    env_file:
    - backend/.env
    # environment:
    # - MONGOPORT=27017
    build: backend
    ports:
    - "3000:3000"
    links: # link service to database
    - database
    networks:
    - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    # - "80:80" # for the server
    - "81:80" # for me locally
    - "445:443"
    networks:
    - app-network

  # Mongo Service
  database:
    image: mongo:3.6-xenial
    container_name: database
    # env_file:
    # - db/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    tty: true
    ports:
    # - "27018:27017" # my laptop
    - "27017:27017" # my server
    networks:
    - app-network
    command: mongod

# Networks
networks:
  app-network:
    driver: bridge
