version: '3'

services:
  # Frontend Service
  vue: # name of service
    build: frontend # dir of dockerfile
    restart: unless-stopped
    tty: true
    ports:
    - "8080:80" # map ports
    networks:
    - app-network

  # Backend Service
  # python:
  #   container_name: python
  #   restart: unless-stopped
  #   environment:
  #   - MONGOPORT=27017
  #   build: backend
  #   ports:
  #   - "3000:3000"
  #   links: # link service to database
  #   - database
  #   networks:
  #     - app-network

  api:
    container_name: api
    restart: unless-stopped
    environment:
    - MONGOPORT=27017
    build: gobackend
    ports:
    - "3000:12345"
    links: # link service to database
    - database
    networks:
    - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
    - "80:80"
    - "443:443"
    networks:
    - app-network

  # Mongo Service
  database:
    image: mongo:3.6-xenial
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
    - "27017:27017"
    networks:
    - app-network

# Networks
networks:
  app-network:
    driver: bridge
